sensors:
  - sensor_plugin: occupancy_map_monitor/PointCloudOctomapUpdaterHaptic
    point_cloud_topic: /pcl
    max_range: 1000.0
    point_subsample: 1
    padding_offset: 0.1 #0.05 #0.1
    padding_scale: 10.0 #10.0 #1.0
    filtered_cloud_topic: filtered_cloud